"""Evidence-reviewed labels; this is a transparent assistant assessment, not a gold standard."""
import json,collections
from pathlib import Path
D=Path(__file__).resolve().parents[1]/'data/followup'
# Each judgment was written after inspecting the stored record fields and recovered source excerpts.
C={
'R':'Representation / selective summary',
'S':'Documented source differences',
'G':'Documentation gap; provenance unresolved',
'L':'Explicit source limitation',
'O':'Reviewer claim overstated or contradicted',
'W':'Inherited wording or citation convention',
'A':'Generated scope ambiguity',
}
# primary category, reasoning, useful action, uncertainty
J={
'S01':('R','download_url is unpopulated, but the FAIRhub access route and conditions are stated in data_governance and external_resources. The historical schema distinguishes a direct data URL from a landing/access page, so this is not proof that download_url should contain that page.','Retain access instructions; populate download_url only if a source supplies an appropriate direct retrieval URL.','No direct-download endpoint was established; no live access test.'),
'S02':('S','The D4D preserves two source statements: FAIRhub says no identifiers were collected and no active de-identification was necessary; the Nature comment says the public set is stripped using Safe Harbor. The comment itself accepts a coherent interpretation.','Attribute each statement to its source and release scope rather than treating either as established false.','The actual processing history is not resolved by these documents.'),
'S03':('S','Both quoted de-identification statements are present in the D4D and recoverable from separate source chunks. This is a source tension carried into the record, not evidence of an invented statement.','Separate source-specific statements and distinguish collection from public-release filtering.','Historical-publication and current-metadata scope may differ; no operational adjudication.'),
'S04':('S','The record explicitly reports conflicting institutions and publisher values. Source excerpts name Washington University in St. Louis in the license/FAIRhub metadata and University of Washington in RO-Crate investigator affiliation.','Preserve role-specific attribution and the source caveat. Seek steward clarification before choosing a single institution.','Different organizational roles can coexist; the sources alone do not prove which attribution is wrong.'),
'S05':('L','The field is absent, and the historical FAIRhub healthsheet explicitly says a data protection impact analysis has not been conducted. The assessment artifact is a source-level absence; the negative statement itself could have been captured.','Populate an explicit negative finding with its source, without inventing a DPIA or interpreting scattered privacy discussion as a formal assessment.','No conclusion about whether a formal assessment is legally required.'),
'S06':('S','The same tension noted in S02 appears in two sources and is reproduced in the same record. The reviewer gives it a stronger interpretation here, but those documents do not determine whether collection and release filtering describe one processing step.','Make the source and processing-stage distinction explicit.','A same-step contradiction cannot be established from the available excerpts.'),
'S07':('S','The record names differing institutions and discloses the provenance of each. The review infers that accountability cannot lie with an institution not listed for operational oversight; that inference is not established by the source excerpts.','Keep organizational role and source attached to each attribution.','The accountable organization cannot be independently settled here.'),
'S08':('R','Device heterogeneity and image-quality variation are documented outside known_biases; known_biases lacks a measurement-bias entry. Adding that taxonomy entry is an interpretive categorization improvement, not proof a source fact was omitted.','Consider a qualified measurement-bias entry that cites the documented device/site heterogeneity and labels the risk as an interpretation.','The inference from heterogeneous devices to systematic bias is not empirically tested.'),
'S09':('G','collection_timeframes supplies grant dates and explicitly says these are not admission dates. The source excerpt confirms the grant period. The clinical temporal-coverage gap is real in the D4D.','Record clinical coverage as not established in the reviewed sources and request release-specific dates.','A targeted source review does not prove no relevant dates exist anywhere in the corpus.'),
'S10':('S','The website and webinar contain the reported numbers, and the record preserves the August 2025 qualifier and images-versus-admissions distinction. Different dates and units do not by themselves establish conflicting facts.','Present numbers in a source/date/unit table; avoid treating all numerical differences as contradictions.','Comparable release snapshots are not available to adjudicate an error.'),
'S11':('S','The source numbers and their qualifiers are preserved. The D4D explicitly says the imaging counts use different units. The reviewer correctly identifies unresolved release-volume specificity, but not a demonstrated inaccurate number.','Use a source/date/unit comparison and distinguish snapshot coverage from current-release counts.','No current release audit was performed.'),
'S12':('O','license_and_use_terms.source_caveats explicitly says the MIT statement concerns software, not data, and identifies the training-program access route. This contradicts the allegation that the D4D conflates software and data licensing. Missing named data-license details remain a separate valid concern.','Withdraw or qualify the conflation allegation while retaining the narrower documentation gap.','This is a mixed comment; it is not wholly invalid.'),
'S13':('G','Both prohibited_uses and discouraged_uses are absent. The source excerpt requires a signed agreement but does not supply its restrictions. The comment’s suggestion that specific prohibitions are presumably in that agreement is speculation.','Mark the unprovided agreement terms as unknown; do not invent prohibitions based on expected practice.','The unavailable agreement was not obtained or adjudicated.'),
'S14':('R','Controlled access is explicitly documented, while regulatory_restrictions is unpopulated. This is a structural classification gap, not an internal contradiction. HIPAA compliance cannot be inferred simply from controlled access.','Preserve the access restriction; fill a regulatory classification only when supported by a source or clearly labeled mapping.','No compliance determination is made.'),
'S15':('W','The misspelled contact domain appears verbatim in the recovered website chunk and is explicitly caveated in the D4D. Its origin is upstream rather than generator invention.','Retain the original string with a warning; verify a replacement with the steward before correcting the address.','Deliverability was not tested, so the claim that it is unusable is unverified.'),
'S16':('O','splits.split_details itself says the award abstract states the dataset will provision a holdout set, and source_caveats calls this an intention. A reader of splits is therefore not being told unambiguously that a realized holdout exists.','Retain the future-tense qualifier; consider a dedicated status field if the schema permits it.','Tasks may still benefit from clearer temporal scope; this does not invalidate the entire comment.'),
'S17':('G','anomalies and missing_data_documentation are absent; cleaning_strategies reports ongoing quality control. The relevant preprint says the data are being QCed. Detailed QC in the Nature paper concerns a different U2OS dataset and cannot be imported indiscriminately.','Seek release-specific QC outcomes, exclusions, and missingness information.','No exhaustive source-availability verdict or extraction-error claim.'),
'S18':('G','preprocessing_strategies and machine_annotation_tools are unpopulated, while notes identify the cell-map pipeline as producing outputs excluded from the release. The current release source also says predicted cell maps are not included.','Prioritize documentation of the processing that produced the distributed archives, with source-specific roles.','The absence of a named production tool in this record does not establish that no source provides one.'),
'S19':('R','The Dataverse retrieval route is already structured in distribution_formats.access_urls. The historical schema says download_url points directly to data rather than a landing page. This correctness-labeled comment is not evidence of an inaccurate value.','Do not automatically copy the landing page into download_url; retain the structured access route.','No file-level direct endpoint was established.'),
'S20':('A','The acquisition field describes three conditions from the preprint, while description/file inventory limits this release’s AP-MS to treated conditions. The field includes preprint-era context, but its relationship to the release could be clearer.','Label the acquisition passage as project/preprint context and state that current AP-MS release coverage is treated conditions only.','This is a scope-clarity issue, not proof the acquisition history is false.'),
'S21':('G','The D4D names MassIVE/Figshare without component accessions. The current-release source likewise names repositories; the explicit identifiers found in the Nature source refer to separate U2OS work.','Mark component identifiers as unprovided in the reviewed release text; obtain release-specific links rather than borrowing unrelated accessions.','No exhaustive search of external repositories was performed.'),
'S22':('O','The compared version strings belong to different DOI-identified Dataverse deposits, each of which has its own version. Source excerpts confirm Version 2.0 for June 2026 and Version 2.1 for earlier deposits. Lower local deposit versions do not demonstrate chronological regression across datasets.','Revise the reviewer’s regression claim; add a per-deposit version clarification if desired.','This is a source/deposit interpretation, not a replacement score.'),
'S23':('W','The keyword mass spectroscopy is present in the D4D and verbatim in the current Dataverse release metadata; the preprint also uses the phrase. It is inherited source terminology rather than evidence of a generator-created substitution.','For controlled-vocabulary indexing, propose normalization to mass spectrometry with source attribution retained.','The review does not quantify any actual search failure.'),
'S24':('O','The same current-release source displays Version 2.0 and supplies a recommended citation ending V2. The D4D preserves both conventions. Different display precision is not by itself a conflicting version claim.','Do not count V2 versus 2.0 as an established factual error.','No claim is made about arbitrary version strings; this case has a matching source citation.'),
'S25':('R','variables has four entries, while file_collections describes more feature arrays and external JSON dictionaries. The D4D is a selective schema summary, not a full variable dictionary. The limited coverage is real but does not mean all variable semantics are absent.','Link or inventory the relevant dictionaries and state the scope of variables; extract additional named variables only where supported.','Column-level completeness cannot be scored without an expected-variable inventory for this release.'),
'S26':('S','The cadence statement comes from older Health Data Nexus documentation and is caveated as such. PhysioNet history mixes major releases and patches. The statements differ in platform/time scope and planned cadence versus observed events.','Move the older cadence to historical context and distinguish planned major-release cadence from patch releases.','Irregular realized releases do not alone falsify a stated plan.'),
'S27':('W','The recovered official recommended citation includes RRID:SCR_007345 alongside PhysioNet and the dataset DOI, matching the D4D citation convention. This establishes inheritance, not a generator-created identifier error.','Preserve the recommended citation and, if useful, explicitly label the repository identifier separately from the dataset DOI.','The RRID registry was not independently resolved during this local review.'),
'S28':('R','The record contains bare B2AI CURIEs without local explanatory labels. This supports a standalone-readability concern, but the reviewer’s claim that prefixes are not resolvable was not tested.','Add labels and an explicit prefix map for standalone exports if the schema/export format supports them.','No ontology-resolution or correctness check of the selected ontology terms was performed.'),
'S29':('G','Subpopulation categories and imbalance are described without counts; criteria are referred to rather than fully enumerated. The source bundle has protocol inclusion criteria, but these are project/time-scoped and do not establish current-release cohort counts.','Separate missing release-specific distributions from protocol detail that could be summarized with date/scope attribution.','No expected demographic table or complete release-specific criteria list was reconstructed.'),
'S30':('O','The historical schema expressly requires a bare DOI in doi and allows a CURIE in id. Thus the mixed rendering is expected, not an identifier inconsistency. The same comment also identifies a genuinely absent publisher field, whose information appears elsewhere.','Remove the DOI-format allegation; retain publisher as a separate representation/completeness observation.','Compound comment with one contradicted and one supported component.'),
'S31':('L','data_protection_impacts explicitly records that no analysis was conducted; the historical source gives the same negative response. A populated negative declaration is not an inaccurate result merely because the underlying dataset has privacy risks.','Keep the negative declaration and distinguish evaluation of documentation fidelity from evaluation of the dataset’s governance practices.','No legal requirement or adequacy determination is made.'),
'S32':('A','The adult-release description says participants were recruited from five categories including pediatric disorders, and collection_mechanisms includes a pediatric process. Other fields correctly identify pediatric data as a separate release. This is a supported scope-clarity problem in generated wording.','Revise the adult-release description to four adult disease categories plus controls; describe pediatric categories only as a separate consortium dataset.','The underlying adult/pediatric dataset separation is explicit in sources; no records were inspected.'),
}
S=json.loads((D/'sample_selection.json').read_text());out=[]
for s in S:
 code,reason,action,uncertainty=J[s['sample_id']];ev=json.loads((D/f"{s['sample_id']}_evidence.json").read_text())
 out.append({**s,'primary_disposition':C[code],'assessment':reason,'recommended_action':action,'uncertainty':uncertainty,'reviewer':'Codex assistant evidence assessment','status':'provisional; human review recommended','basis':'frozen D4D fields plus selected recovered source excerpts; historical schema for S01/S19/S30','evidence_file':f"{s['sample_id']}_evidence.json",'source_excerpt_count':len(ev['source_excerpts'])})
(D/'sample_assessments.json').write_text(json.dumps(out,indent=2))
(D/'disposition_definitions.json').write_text(json.dumps({'categories':C,'limitations':['One primary label per compound comment is a summary; read the component-level explanation.','The balanced 32-comment sample is not a prevalence estimate for all 562 comments.','Source searches are targeted and non-exhaustive; absence of a match does not prove source absence.','No reviewer precision/recall or factual error rate is estimated.','No original D4D, score, or evaluator text was changed.']},indent=2))
print(dict(collections.Counter(x['primary_disposition'] for x in out)))
