"""Size-normalized section report fragment."""
from pathlib import Path
import json,base64
O=Path(__file__).resolve().parent
load=lambda n:json.loads((O/'data'/f'{n}.json').read_text())
def render(table,details):
 parts=['''<h2 id="size-normalized">Do section differences persist after accounting for size?</h2><p><b>Yes, differences remain after normalizing scoring opportunities, but the leading sections depend on the measure and dataset.</b> The analysis below separates each section’s <em>loss rate</em> from its <em>contribution to total score loss</em>. It also tests three field denominators for negative comments. These are arithmetic normalizations, not a fitted model of dataset-independent section effects.</p><h3>Score-loss rate versus contribution</h3><p>Across the 12 v8 records, rubric10 loses <b>76 of 591 applicable points (12.9%)</b>. Metadata accounts for the most lost points among mapped sections: <b>17 points, or 22.4% of all loss</b>. Its normalized loss rate is 17/108 = <b>15.7%</b>. Variables loses fewer points overall (6, or 7.9% of total loss), but has the largest normalized rate: <b>6/12 = 50%</b>. Preprocessing loses 3/12 (25%) and Maintenance 8/36 (22.2%).</p><div class="note"><b>The crosswalk is partial.</b> The existing 39-item rubric10 mapping explains 54 of the 76 lost points. The remaining <b>22 lost points (28.9%)</b> belong to 11 unmapped items and appear as a separate row. Variables, Preprocessing, and several other sections have only one mapped item per record. FileCollection has none. These are selected-item section profiles, not complete section scores; rubric20 deductions are not allocated here.</div>''']
 figs=[('12_v8_section_loss_normalized','Figure 12. Loss rate = summed lost points / summed applicable points in the section. Contribution = section lost points / all 76 lost rubric10 points, including unmapped items. Numerators and denominators appear beside the left panel. Each item is assigned to at most one section, so contributions do not double-count deductions. This point-weighted rate can differ from the earlier equal-record mean when applicability varies.'),('13_v8_section_flag_denominators','Figure 13. Unique flagged record–root pairs / eligible record–root pairs. The numerator is intersected with the denominator’s field set. Both rubrics contribute flags, but repeated comments count only once per pair. Candidates = 98 roots in the retained crosswalk, including unpopulated and potentially inapplicable roots; Populated = nonempty roots; Receipt-linked = populated roots with a declared receipt link. The latter two exclude omissions. These are denominator sensitivity analyses, because field applicability has not been adjudicated.'),('14_v8_section_loss_consistency','Figure 14. Section loss rates computed separately in each dataset, pooling three generations. Variables loses all available points in CHORUS and CM4AI and none in AI_READI or VOICE. Preprocessing’s loss occurs entirely in CM4AI. Maintenance loss occurs in CHORUS and CM4AI. The pooled pattern is therefore not uniform across dataset contexts.')]
 for i,(name,cap) in enumerate(figs):
  if i==1:parts.append('''<h3>Negative-comment concentration after field-count normalization</h3><p>Metadata and Composition each had 11.4 raw section comments per record. They separate after normalization: <b>36.4% versus 61.3%</b> of mapped candidate record–field pairs are flagged. The corresponding populated-field rates are <b>37.6% versus 68.8%</b>, and receipt-linked populated rates are <b>44.3% versus 69.5%</b>. Thus Composition has more concentrated root-level criticism than Metadata under all three definitions, despite equal raw comment counts.</p><p><b>Root count is only one measure of section size.</b> FileCollection and Variables each have one mapped root that may contain many nested entries. Their high flag proportions cannot establish higher error density per nested field, claim, file, or word. Candidate denominators include optional fields; populated and linked denominators hide omissions. None is a verified applicable-field denominator.</p>''')
  if i==2:parts.append('''<h3>Consistency across records and datasets</h3><p>The table below also compares each section’s normalized loss with the other mapped sections <em>in the same record</em>, and recomputes section loss after omitting each dataset in turn. This checks whether a pooled result is driven by a particular dataset without treating the 12 generations as independent datasets.</p>''')
  b=base64.b64encode((O/'figures'/f'{name}.png').read_bytes()).decode();parts.append(f'<figure><img alt="{name.replace("_"," ")}" src="data:image/png;base64,{b}"><figcaption>{cap} <a href="figures/{name}.svg">SVG</a> · <a href="figures/{name}.png">PNG</a></figcaption></figure>')
 parts.append(details('Score-loss totals, normalized rates, and contribution shares',load('size_score_summary')))
 parts.append(details('Within-record comparison and leave-one-dataset-out sensitivity',load('size_score_robustness')))
 parts.append(details('Field denominators, numerators, and omitted-field flags',load('size_field_summary')))
 rows=load('size_source_field_summary')
 parts.append(details('Size-normalized comments by supplied document family (all denominator definitions)',[r for r in rows if r['level']=='family' and r['outcome']=='Any comment'],['document_type','section','denominator_definition','available_records','eligible_records','flagged_record_field_pairs','eligible_record_field_pairs','pooled_percent']))
 parts.append('''<p>The document-family table applies the same field-count normalization to the input-availability cohorts used in Figure 9. All 14 native document types, completeness-only and accuracy/correctness flags, record-level denominators, and paired score comparisons are exported in the linked JSON tables. The already-normalized receipt-linked family view in Figure 11 averages records equally; this sensitivity table pools record–field pairs, weighting records by the number of eligible fields.</p><p><b>Supported conclusion:</b> In this v8 evaluation, selected rubric10 items associated with Variables have a higher pooled proportion of scoring points lost than those associated with Metadata, although Metadata contributes more lost points overall. Composition has a higher flagged-root proportion than Metadata under all three field definitions. Neither result establishes a universal section ranking or a section effect independent of dataset, item difficulty, rubric coverage, or nested content size.</p>''')
 return ''.join(parts)
