"""HTML fragment for pooled source-type analysis; imported by build_report.py."""
from pathlib import Path
import json,base64
O=Path(__file__).resolve().parent
load=lambda n:json.loads((O/'data'/f'{n}.json').read_text())
def render(table,details):
 a=load('section_document_summary');mix=load('section_document_cohorts');mapping=load('section_document_score_mapping')
 parts=['''<h2 id="pooled-sections">Section scoring and negative comments by input-document type</h2><p>This view pools all 12 v8 records, without separate program or dataset panels. Columns identify the types of documents supplied with each record. A record can appear in several columns because its input bundle contains several document types. Pooling does not statistically adjust for dataset; these are overlapping observational groups.</p><p>The three views answer different questions: <b>how many section comments occur when a document family is available</b>; <b>how selected section-related rubric10 items score in those records</b>; and <b>how often the fields actually linked to that document family are flagged</b>. They should not be interpreted as measuring the same outcome.</p><div class="note"><b>Read the columns as input-bundle profiles, not document rankings.</b> Docs and Awards both occur in all 12 records, so their availability-based columns necessarily match. Publications, Repositories, and Terms also identify the same nine records and therefore have identical availability-based profiles. Structured and Tutorials each represent only one dataset. The receipt-linked view uses different field subsets and can differ even when the available-record cohorts are identical.</div><h3>Where negative comments concentrate</h3><p>Across all 12 records, Composition and Metadata each receive 11.4 section-tagged issue entries per record on average, followed by Data Governance (4.5), FileCollection (4.0), and Human (4.0). This is review burden, not a normalized error rate: larger sections provide more opportunities for comments, and the two rubrics can repeat a concern.</p>''']
 figs=[('09_v8_pooled_section_comments','Figure 9. For each document family, average the number of distinct issue IDs assigned to the section over all records supplied with that family, including records with zero comments. Both primary rubrics contribute. One multi-section comment can enter several rows, so row counts cannot be summed as distinct errors. The tables retain all five native comment categories.'),('10_v8_pooled_section_scores','Figure 10. A conservative analyst crosswalk assigns 39 of 50 rubric10 subelements to a single schema section; 11 broad or ambiguous items are excluded. First compute each record’s applicable mapped-item percentage, then average records equally within the supplied-document cohort. This is a partial section profile, not an official section score. N/A means no applicable mapped item. The Human row has fewer scored records because applicable items vary.'),('11_v8_pooled_linked_flags','Figure 11. For each record, section, and document family, deduplicate the populated root fields linked by receipts. Count the fraction named in any negative comment from either rubric, then average those fractions equally over eligible records. Repeated chunks and repeated flags do not inflate the fraction. Only records with at least one eligible linked root enter the cell; absent roots and unlinked content are excluded. A root-level flag may concern another claim within that field, so linkage does not attribute the concern to a source.')]
 for k,(name,cap) in enumerate(figs):
  if k==1:parts.append('<h3>Selected section-related scores</h3><p>Using the all-record cohort, the selected Variables item averages 50%, the Preprocessing item 75%, and the three Maintenance items 77.8%. Collection, Distribution, Motivation, and Uses average 100% on their selected items despite receiving negative comments. Binary rubric10 criteria and detailed semantic comments measure different things; a full item score does not certify an entire section as correct.</p>')
  if k==2:parts.append('<h3>Comments on fields linked to each document family</h3><p>This narrower view uses receipt support rather than input availability. It describes the reviewed fields associated with a source family, while retaining the section context.</p>')
  b=base64.b64encode((O/'figures'/f'{name}.png').read_bytes()).decode();parts.append(f'<figure><img alt="{name.replace("_"," ")}" src="data:image/png;base64,{b}"><figcaption>{cap} <a href="figures/{name}.svg">SVG</a> · <a href="figures/{name}.png">PNG</a></figcaption></figure>')
 parts.append(details('Document availability: sample sizes for all eight families and 14 native types',mix,['level','document_type','records','datasets']))
 parts.append(details('Exact rubric10 item-to-section mapping, including all exclusions',mapping))
 keys=['document_type','section','available_records','mean_comments_per_record','section_flagged_records','completeness_comments','consistency_comments','content_accuracy_comments','correctness_comments','semantic_understanding_comments']
 parts.append(details('Negative comments by section and document family: counts and record coverage',[x for x in a if x['level']=='family'],keys))
 parts.append(details('Native document types: section comments (no family grouping)',[x for x in a if x['level']=='native'],keys))
 keys=['document_type','section','available_records','mapped_items','score_records','mean_selected_r10_percent','linked_records','linked_datasets','linked_record_field_pairs','linked_flagged_pairs','mean_linked_flagged_percent']
 parts.append(details('Native document types: scores and receipt-linked flag fractions',[x for x in a if x['level']=='native'],keys))
 parts.append('<p><b>Limits on claims.</b> These data support statements about observed section profiles in v8 input bundles. They do not show that adding a document type changes scores or reduces comments independently of the dataset. No significance tests are added: overlapping cohorts, only four dataset contexts, and source types tied to individual datasets limit such inference. The source grouping, record-level denominators, included/excluded score items, and unrounded native-type estimates are exported for inspection.</p>')
 return ''.join(parts)
