#!/usr/bin/env python
"""Regenerate the cross-arm comparison slide deck as a PDF.

Every figure page embeds a PNG regenerated by scripts/arm_comparison.py, so
run that first; the receipt/review numbers are read live from the provenance
records at build time. Output: notes/arm_comparison_deck_<date>[_partial].pdf.
"""
from __future__ import annotations

import datetime
import glob
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import yaml
from matplotlib.backends.backend_pdf import PdfPages

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "notes" / "figures"
CORE = ROOT / "data" / "d4d_concatenated" / "claudecode_agent_core"

FIGURES = [  # (png, slide title)
    ("arm_comparison_leaves.png", "populated leaves (coverage)"),
    ("arm_comparison_rubric10.png", "rubric10-semantic (canonical records)"),
    ("arm_comparison_rubric20.png", "rubric20-semantic (canonical records)"),
    ("arm_comparison_noreceipt.png", "slots without a receipt"),
    ("arm_comparison_unreviewed.png", "chunks unreviewed"),
    ("arm_comparison_unverified.png", "snippets unverified"),
    ("arm_comparison_wrongchunk.png", "snippets not in the chunk cited"),
    ("arm_comparison_gc.png", "GC label variants (reported)"),
    ("arm_comparison_partial_review_adverse.png", "d4d-review-record: slot adverse rate"),
    ("cross_read_r20_vs_adverse.png", "cross-read: rubric score vs review adverse rate"),
]


def receipt_rows() -> list[tuple[str, str, int, int, int, int, str]]:
    rows = {}
    for f in glob.glob(str(CORE / "2026-08-*" / "*_provenance.yaml")):
        d = yaml.safe_load(open(f))
        rc = d.get("receipts") or {}
        if not rc.get("checked"):
            continue
        label = Path(f).parent.name
        arm = ("agentic v6" if "claudecode-generic-v6" in label
               else "API v7 canary (excluded)" if "2026-08-28" in label
               else "API v7 production" if "api-generic-v7" in label else None)
        if arm is None:
            continue
        r = rows.setdefault(arm, [0, 0, 0, 0, 0])
        sn, sl = rc.get("snippets") or {}, rc.get("slots") or {}
        r[0] += 1
        r[1] += int(sn.get("verified") or 0); r[2] += int(sn.get("total") or 0)
        r[3] += int(sl.get("with_receipt") or 0); r[4] += int(sl.get("receiptable") or 0)
    return [(a, *v) for a, v in sorted(rows.items())]


def text_page(pdf: PdfPages, title: str, lines: list[str]) -> None:
    fig = plt.figure(figsize=(13.33, 7.5))
    fig.text(0.05, 0.92, title, size=22, weight="bold")
    fig.text(0.06, 0.84, "\n\n".join(lines), size=12, va="top", wrap=True)
    pdf.savefig(fig); plt.close(fig)


def image_page(pdf: PdfPages, png: Path, title: str) -> None:
    fig = plt.figure(figsize=(13.33, 7.5))
    fig.text(0.05, 0.93, title, size=20, weight="bold")
    ax = fig.add_axes([0.03, 0.05, 0.94, 0.83]); ax.axis("off")
    ax.imshow(mpimg.imread(png))
    pdf.savefig(fig); plt.close(fig)


def main() -> int:
    partial = "--final" not in sys.argv
    today = datetime.date.today().isoformat()
    out = ROOT / "notes" / f"arm_comparison_deck_{today}{'_partial' if partial else ''}.pdf"
    with PdfPages(out) as pdf:
        text_page(pdf, "D4D generation arms — cross-arm comparison", [
            f"Regenerated {today} from the provenance records "
            "(scripts/arm_comparison.py + scripts/arm_deck.py). "
            + ("STATUS: INTERMEDIATE — the v7 production arm (2026-08-31 matrix) is "
               "in progress; v7 bars are the excluded 2026-08-28 exploratory canaries "
               "unless labeled production." if partial else
               "The v7 arm is the 2026-08-31 production matrix (12 records); the five "
               "2026-08-28 canaries are excluded from all statistics per the adopted decision."),
            "Arms: v4 API (2026-08-13) · v5 API (2026-08-22c) · v5 agentic (2026-08-24) · "
            "v6 agentic (2026-08-28, receipt protocol) · v7 API (receipt protocol).",
            "Since the 2026-08-27 deck: chunk manifests and coverage receipts on BOTH arms "
            "(#707-#710), the d4d-review-record pass (17 records), the rubric-vs-review "
            "cross-read (#815: rubric scores track the project, not the record), and the "
            "v7 production protocol (#838/#849).",
        ])
        rr = receipt_rows()
        text_page(pdf, "Receipts: the like-for-like grounding measurement", [
            "Both arms now write a coverage receipt per chunk against the same manifest "
            "and validator. Aggregates (records · snippets verified/total · leaf coverage):",
            "\n".join(f"  {a:26s} {n:2d} records · snippets {v}/{t} · "
                      f"slots with receipt {w}/{r} ({100*w/r:.0f}%)"
                      for a, n, v, t, w, r in rr if r),
            "The agentic arm's 3,400/3,400 verbatim snippets vs the API canaries' "
            "adjacent/mismatched residue is the grounding story the rubric pages cannot "
            "see — see the cross-read slide.",
        ])
        # One row per record carrying a review.reliability block — globbed,
        # not hardcoded, so a seventh double-review appears by itself (#871);
        # per-record try so one bad record drops one named row (#869).
        rel = []
        for f in sorted(CORE.glob("*/*_provenance.yaml")):
            try:
                r = (yaml.safe_load(open(f)).get("review") or {}).get("reliability")
                if not r:
                    continue
                proj = f.name.split("_prov")[0]
                label = f.parent.name
                tag = ("v7 " if "api-generic" in label else "v6 ") + label.rsplit("_", 1)[1]
                adj = r.get("adjudication") or {}
                rel.append(f"  {proj:9s} {tag:8s} kappa {r['kappa_class']}  adverse {r['adverse_a']} vs "
                           f"{r['adverse_b']}  adjudicated (Codex) A {adj.get('a_right','-')} / B {adj.get('b_right','-')}")
            except Exception as e:                            # noqa: BLE001
                rel.append(f"  {f}: unavailable ({type(e).__name__})")
        text_page(pdf, "Review reliability and adjudication", [
            "Six records double-reviewed against the same committed packs (test-retest): "
            "pooled kappa 0.534 [0.41, 0.65] over 402 paired items, class agreement 89.1%. "
            "Chunk verdicts 100% stable; disagreement sits at weak/supported and rule boundaries. "
            "Rows show the cross-vendor (Codex) adjudication splits.",
            "\n".join(rel),
            "All 44 disagreements adjudicated twice: claude-sonnet-5 (same family; A 24 / B 19 / neither 1) "
            "and OpenAI Codex via codex-personal, direct CLI (cross-vendor; A 28 / B 16 / 0). The two agree "
            "on 34/44 and both uphold the original raters' strictness — single-rating adverse rates are "
            "reporting-grade, not a selection criterion (#660). "
            "Sources: notes/review_reliability_2026-09-01.md, notes/adjudication_*.md.",
        ])
        for png, title in FIGURES:
            p = FIG / png
            if p.exists():
                image_page(pdf, p, title + ("  [intermediate]" if partial and "review_adverse" in png else ""))
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
